#!/bin/sh
# $Id: pause 1521 2006-06-28 13:53:39Z geggo $
: ${DIALOG=dialog}

$DIALOG --title "PAUSE" --pause "Hi, this is a pause widget" 20 70 10

retval=$?

case $retval in
  0)
    echo "Timeout expired.";;
  1)
    echo "Cancel pressed.";;
  *)
    echo "Unexpected return code: $retval";;
esac
