#!/bin/sh
# $Id: timebox2-stdout 1521 2006-06-28 13:53:39Z geggo $
: ${DIALOG=dialog}

USERTIME=`$DIALOG --stdout --title "TIMEBOX" --timebox "Please set the time..." 0 0`

case $? in
  0)
    echo "Time entered: $USERTIME.";;
  1)
    echo "Cancel pressed.";;
  255)
    echo "Box closed.";;
esac
