#ifdef TRIXPLUG_MODE

#define trixplug_get ft->trixplug->get
#define trixplug_handle_load ft->trixplug->handle_load
#define trixplug_load_plugin ft->trixplug->load_plugin
#define trixplug_get_plugin_entry ft->trixplug->get_plugin_entry
#define trixplug_unload_plugin ft->trixplug->unload_plugin
#define trixplug_add_plugin_header ft->trixplug->add_plugin_header
#define trixplug_add_plugin_symbol ft->trixplug->add_plugin_symbol
#define trixplug_get_global_plugin_symbol ft->trixplug->get_global_plugin_symbol
#define trixplug_get_plugin_symbol ft->trixplug->get_plugin_symbol
#define trixplug_get_plugins ft->trixplug->get_plugins
#define trixplug_set_notification ft->trixplug->set_notification
#define trixplug_notify ft->trixplug->notify
#define trixplug_init ft->trixplug->init

#define segment_duplicate ft->segment->duplicate
#define segment_find_by_num ft->segment->find_by_num
#define segment_find_by_end_and_name ft->segment->find_by_end_and_name
#define segment_find_by_end ft->segment->find_by_end
#define segment_find_by_start ft->segment->find_by_start
#define segment_find_by_name ft->segment->find_by_name
#define segment_count ft->segment->count
#define segment_is_mapped ft->segment->is_mapped
#define segment_is_sparse ft->segment->is_sparse
#define segment_map_in_mem ft->segment->map_in_mem
#define segment_hide_in_mem ft->segment->hide_in_mem
#define segment_get_last ft->segment->get_last
#define segment_add ft->segment->add
#define segment_create ft->segment->create
#define segment_dump ft->segment->dump
#define segment_release ft->segment->release
#define segment_release_all ft->segment->release_all

#define stage_merge ft->stage->merge
#define stage_get_start ft->stage->get_start
#define stage_get_end ft->stage->get_end
#define stage_has_unmapped ft->stage->has_unmapped
#define stage_has_overlaps ft->stage->has_overlaps
#define stage_replace ft->stage->replace
#define stage_duplicate ft->stage->duplicate
#define stage_add ft->stage->add
#define stage_create ft->stage->create
#define stage_find_by_num ft->stage->find_by_num
#define stage_get_last ft->stage->get_last
#define stage_restore_info ft->stage->restore_info
#define stage_release_info ft->stage->release_info
#define stage_save_info ft->stage->save_info
#define stage_count ft->stage->count
#define stage_get_num ft->stage->get_num
#define stage_get_segments ft->stage->get_segments
#define stage_dump ft->stage->dump
#define stage_get ft->stage->get
#define stage_clear_flags ft->stage->clear_flags
#define stage_get_modified ft->stage->get_modified
#define stage_get_savestage ft->stage->get_savestage
#define stage_get_workspace ft->stage->get_workspace
#define stage_set_modified ft->stage->set_modified
#define stage_set_savestage ft->stage->set_savestage
#define stage_set_workspace ft->stage->set_workspace
#define stage_get_current ft->stage->get_current
#define stage_release ft->stage->release
#define stage_release_all ft->stage->release_all

#define file_io_create_empty ft->file_io->create_empty
#define file_io_create_directory ft->file_io->create_directory
#define file_io_open_directory ft->file_io->open_directory
#define file_io_open ft->file_io->open
#define file_io_write ft->file_io->write
#define file_io_release ft->file_io->release
#define file_io_release_all ft->file_io->release_all

#define file_set_options ft->file->set_options
#define file_get_options ft->file->get_options
#define file_open ft->file->open
#define file_flush_diff ft->file->flush_diff
#define file_flush ft->file->flush
#define file_sync ft->file->sync
#define file_format ft->file->format
#define file_write ft->file->write
#define file_release ft->file->release
#define file_release_all ft->file->release_all

#define workspace_skip_error ft->workspace->skip_error
#define workspace_set_modified ft->workspace->set_modified
#define workspace_startup ft->workspace->startup
#define workspace_create ft->workspace->create
#define workspace_create_file ft->workspace->create_file
#define workspace_create_file_from_buffer ft->workspace->create_file_from_buffer
#define workspace_add_file ft->workspace->add_file
#define workspace_memmap_add ft->workspace->memmap_add
#define workspace_release ft->workspace->release
#define workspace_memmap_release ft->workspace->memmap_release
#define workspace_memmap_sort ft->workspace->memmap_sort
#define workspace_memmap_reverse ft->workspace->memmap_reverse
#define workspace_update_memmap ft->workspace->update_memmap

#define util_init ft->util->init
#define util_set_debuglevel ft->util->set_debuglevel
#define util_set_errorlevel ft->util->set_errorlevel
#define util_script_is_aborted ft->util->script_is_aborted
#define util_get_line ft->util->get_line
#define util_smalloc_init ft->util->smalloc_init
#define util_smalloc ft->util->smalloc
#define util_dump_bytes ft->util->dump_bytes
#define v_cache_update ft->util->v_cache_update
#define v_cache_flush ft->util->v_cache_flush
#define v_get_size ft->util->v_get_size
#define v_get_segment ft->util->v_get_segment
#define v_get_areas ft->util->v_get_areas
#define v_get_start ft->util->v_get_start
#define v_get_end ft->util->v_get_end
#define v_set_b ft->util->v_set_b
#define v_set_h ft->util->v_set_h
#define v_set_w ft->util->v_set_w
#define v_set_b_raw ft->util->v_set_b_raw
#define v_set_h_raw ft->util->v_set_h_raw
#define v_set_w_raw ft->util->v_set_w_raw
#define v_get_b ft->util->v_get_b
#define v_get_h ft->util->v_get_h
#define v_get_w ft->util->v_get_w
#define v_get_b_raw ft->util->v_get_b_raw
#define v_get_h_raw ft->util->v_get_h_raw
#define v_get_w_raw ft->util->v_get_w_raw
#define v_get_strlen ft->util->v_get_strlen
#define v_get_str ft->util->v_get_str
#define v_get_strlen_raw ft->util->v_get_strlen_raw
#define v_get_str_raw ft->util->v_get_str_raw
#define v_get_ptr ft->util->v_get_ptr
#define v_valid ft->util->v_valid
#define v_get_next_offset ft->util->v_get_next_offset
#define v_get_prev_offset ft->util->v_get_prev_offset
#define v_arch_h ft->util->v_arch_h
#define v_arch_w ft->util->v_arch_w
#define v_valid_raw ft->util->v_valid_raw
#define v_memcpy_get_raw ft->util->v_memcpy_get_raw
#define v_memcpy ft->util->v_memcpy
#define v_memcpy_get ft->util->v_memcpy_get
#define v_memcpy_put ft->util->v_memcpy_put
#define util_swap_half ft->util->swap_half
#define util_swap_word ft->util->swap_word
#define is_type ft->util->is_type
#define util_hex_get ft->util->hex_get
#define util_hex_get_buffer ft->util->hex_get_buffer
#define util_hexunpack ft->util->hexunpack
#define util_hexpack ft->util->hexpack
#define util_list_get_last ft->util->list_get_last
#define util_list_add ft->util->list_add
#define util_list_add_new ft->util->list_add_new
#define util_list_free ft->util->list_free
#define util_list_count ft->util->list_count
#define util_check_pattern ft->util->check_pattern
#define util_check_pattern_raw ft->util->check_pattern_raw
#define util_quick_find_pattern ft->util->quick_find_pattern
#define util_simple_find_pattern ft->util->simple_find_pattern
#define util_find_pattern ft->util->find_pattern
#define util_block_get_size ft->util->block_get_size
#define util_block_get_segment_count ft->util->block_get_segment_count
#define util_block_get_segment_name_ptr ft->util->block_get_segment_name_ptr
#define util_str2int ft->util->str2int
#define util_block_get_number ft->util->block_get_number
#define util_block_get_val_ptr ft->util->block_get_val_ptr
#define util_block_get_offset_ptr ft->util->block_get_offset_ptr
#define util_block_get_data_pointer ft->util->block_get_data_pointer
#define util_free_object ft->util->free_object
#define util_dump_object ft->util->dump_object
#define util_split ft->util->split
#define util_cache_enable ft->util->cache_enable
#define util_cache_disable ft->util->cache_disable

#define elf_free_object ft->elf->free_object
#define elf_get_tab ft->elf->get_tab
#define elf_get_symtab ft->elf->get_symtab
#define elf_get_reloc ft->elf->get_reloc
#define elf_get_strtab ft->elf->get_strtab
#define elf_byteswap_rel ft->elf->byteswap_rel
#define elf_byteswap_sym ft->elf->byteswap_sym
#define elf_get_string ft->elf->get_string
#define elf_get_section ft->elf->get_section
#define fmt_elf_cify ft->elf->fmt_elf_cify
#define elf_get_section_name ft->elf->get_section_name
#define elf_parse_symtab ft->elf->parse_symtab
#define elf_dump_symtabs ft->elf->dump_symtabs
#define elf_get_symbol ft->elf->get_symbol
#define elf_get_symbol_name ft->elf->get_symbol_name
#define elf_parse_reloc ft->elf->parse_reloc
#define elf_dump_relocs ft->elf->dump_relocs
#define elf_section_used ft->elf->section_used
#define elf_create_object ft->elf->create_object
#define elf_dump_object ft->elf->dump_object

#define crypto_get_signkey ft->crypto->get_signkey
#define crypto_get_signer ft->crypto->get_signer
#define crypto_get_signee ft->crypto->get_signee
#define crypto_get_signopt ft->crypto->get_signopt
#define crypto_get_key ft->crypto->get_key
#define crypto_get_keyname ft->crypto->get_keyname
#define crypto_unfold ft->crypto->unfold
#define crypto_check_integrity ft->crypto->check_integrity
#define crypto_generate_cert ft->crypto->generate_cert
#define crypto_init_algokey ft->crypto->init_algokey
#define crypto_init_algoiv ft->crypto->init_algoiv
#define crypto_encrypt_buffer ft->crypto->encrypt_buffer
#define crypto_decrypt_buffer ft->crypto->decrypt_buffer
#define crypto_generate_key ft->crypto->generate_key
#define crypto_generate_sha1 ft->crypto->generate_sha1
#define crypto_generate_md5 ft->crypto->generate_md5

#define trixcrypt_alloc_priv ft->trixcrypt->alloc_priv
#define trixcrypt_copy_cryptkey ft->trixcrypt->copy_cryptkey
#define trixcrypt_set_decryptkey ft->trixcrypt->set_decryptkey
#define trixcrypt_set_encryptkey ft->trixcrypt->set_encryptkey
#define trixcrypt_set_cryptkeys ft->trixcrypt->set_cryptkeys

#define netrix_check ft->netrix->check
#define netrix_open ft->netrix->open
#define netrix_execute ft->netrix->execute
#define netrix_get ft->netrix->get

#define treenode_create ft->treenode->create
#define treenode_addchild ft->treenode->addchild
#define treenode_append ft->treenode->append
#define treenode_append_child ft->treenode->append_child
#define treenode_append_node ft->treenode->append_node
#define treenode_clone ft->treenode->clone
#define treenode_insert_before ft->treenode->insert_before
#define treenode_insert_at ft->treenode->insert_at
#define treenode_count ft->treenode->count
#define treenode_position ft->treenode->position
#define treenode_prev ft->treenode->prev
#define treenode_next ft->treenode->next
#define treenode_children ft->treenode->children
#define treenode_parent ft->treenode->parent
#define treenode_set_priv ft->treenode->set_priv
#define treenode_get_priv ft->treenode->get_priv
#define treenode_set_name ft->treenode->set_name
#define treenode_set_content_type_raw ft->treenode->set_content_type_raw
#define treenode_set_content_type ft->treenode->set_content_type
#define treenode_set_content_data_raw ft->treenode->set_content_data_raw
#define treenode_set_content_data ft->treenode->set_content_data
#define treenode_set_content_data_binary ft->treenode->set_content_data_binary
#define treenode_set_content_data_integer ft->treenode->set_content_data_integer
#define treenode_set_content_data_hexval ft->treenode->set_content_data_hexval
#define treenode_set_content_data_float ft->treenode->set_content_data_float
#define treenode_set_attributes ft->treenode->set_attributes
#define treenode_get_name ft->treenode->get_name
#define treenode_get_content_type_raw ft->treenode->get_content_type_raw
#define treenode_get_content_type ft->treenode->get_content_type
#define treenode_is_content_type ft->treenode->is_content_type
#define treenode_get_content_data_raw ft->treenode->get_content_data_raw
#define treenode_get_content_data ft->treenode->get_content_data
#define treenode_get_content_ascii ft->treenode->get_content_ascii
#define treenode_get_content_data_integer ft->treenode->get_content_data_integer
#define treenode_get_content_data_hexval ft->treenode->get_content_data_hexval
#define treenode_get_content_data_binary ft->treenode->get_content_data_binary
#define treenode_get_attributes ft->treenode->get_attributes
#define treenode_get_byname ft->treenode->get_byname
#define treenode_release ft->treenode->release
#define treenode_unlink ft->treenode->unlink
#define treenode_dump ft->treenode->dump

#define ui_set_exiting ft->ui->set_exiting
#define ui_register_cb ft->ui->register_cb
#define ui_set_callback_state ft->ui->set_callback_state
#define ui_dlg_msg ft->ui->dlg_msg
#define ui_dlg_tree ft->ui->dlg_tree
#define ui_dlg_dumpmem ft->ui->dlg_dumpmem
#define ui_dlg_dumpmem_set_addr ft->ui->dlg_dumpmem_set_addr
#define ui_dlg_dumpmem_get_addr ft->ui->dlg_dumpmem_get_addr
#define ui_dlg_dumpmem_visible ft->ui->dlg_dumpmem_visible
#define ui_dlg_dumpmem_finish ft->ui->dlg_dumpmem_finish
#define ui_dlg_menu ft->ui->dlg_menu
#define ui_dlg_int ft->ui->dlg_int
#define ui_dlg_bool ft->ui->dlg_bool
#define ui_vprintf_func ft->ui->vprintf_func
#define ui_printf_msg ft->ui->printf_msg
#define ui_debug_msg ft->ui->debug_msg
#define ui_error_msg ft->ui->error_msg
#define ui_dlg_string ft->ui->dlg_string
#define ui_dlg_load_file ft->ui->dlg_load_file
#define ui_dlg_save_file ft->ui->dlg_save_file
#define ui_dlg_box_create ft->ui->dlg_box_create
#define ui_dlg_box_release ft->ui->dlg_box_release
#define ui_dlg_box_release_all ft->ui->dlg_box_release_all
#define ui_dlg_box_msg ft->ui->dlg_box_msg
#define ui_dlg_box_set_keypress_ptr ft->ui->dlg_box_set_keypress_ptr
#define ui_dlg_box_clear ft->ui->dlg_box_clear
#define ui_dlg_box_size ft->ui->dlg_box_size

#define fmt_get_handler ft->fmt->get_handler
#define fmt_decode ft->fmt->decode
#define fmt_encode ft->fmt->encode
#define fmt_encode_diff ft->fmt->encode_diff
#define fmt_free_priv ft->fmt->free_priv
#define fmt_unregister_handler ft->fmt->unregister_handler
#define fmt_register_handler ft->fmt->register_handler
#define fmt_add_seer_entry ft->fmt->add_seer_entry
#define fmt_add_seer ft->fmt->add_seer
#define fmt_update ft->fmt->update
#define fmt_init ft->fmt->init

#define symbols_dump ft->symbols->dump
#define symbols_add ft->symbols->add
#define symbols_remove ft->symbols->remove
#define symbols_free_all ft->symbols->free_all
#define symbols_get ft->symbols->get
#define symbols_get_address ft->symbols->get_address
#define symbols_count ft->symbols->count

#define nokia_init ft->nokia->init
#define nokia_reserve_ram ft->nokia->reserve_ram
#define nokia_release_ram ft->nokia->release_ram
#define nokia_reserve_eeprom ft->nokia->reserve_eeprom
#define nokia_release_eeprom ft->nokia->release_eeprom
#define nokia_is_section_name_relative ft->nokia->is_section_name_relative
#define nokia_get_section_dest ft->nokia->get_section_dest
#define nokia_export_segments ft->nokia->export_segments
#define nokia_fill_section_data ft->nokia->fill_section_data
#define nokia_create_func2 ft->nokia->create_func2
#define nokia_create_func ft->nokia->create_func

#define options_read_settings_real ft->options->read_settings_real
#define options_read_settings ft->options->read_settings
#define options_read_all_settings ft->options->read_all_settings
#define options_get_options ft->options->get_options
#define options_default_all ft->options->default_all
#define options_apply_as_default_state ft->options->apply_as_default_state
#define options_set_default ft->options->set_default
#define options_apply_settings ft->options->apply_settings
#define options_has_default ft->options->has_default
#define options_get_description ft->options->get_description
#define options_get_string ft->options->get_string
#define options_get_int ft->options->get_int
#define options_get_bool ft->options->get_bool
#define options_set_int ft->options->set_int
#define options_set_string ft->options->set_string
#define options_set_bool ft->options->set_bool
#define options_get_type ft->options->get_type
#define options_normalize_optionname ft->options->normalize_optionname
#define options_normalize_pluginname ft->options->normalize_pluginname
#define options_delete_option ft->options->delete_option
#define options_add_option ft->options->add_option
#define options_import_script_options ft->options->import_script_options
#define options_delete_script_options ft->options->delete_script_options
#define options_add_sysvar ft->options->add_sysvar
#define options_import_plugin_options ft->options->import_plugin_options
#define options_delete_plugin_options ft->options->delete_plugin_options
#define options_set_notification ft->options->set_notification
#define options_notify ft->options->notify
#define options_load ft->options->load
#define options_init ft->options->init

#define arm_init ft->arm->init
#define arm_set ft->arm->set
#define arm_set_32 ft->arm->set_32
#define arm_get_bl ft->arm->get_bl
#define arm_get_32 ft->arm->get_32
#define arm_get_32_adv ft->arm->get_32_adv
#define arm_get ft->arm->get
#define arm_get_adv ft->arm->get_adv
#define arm_find ft->arm->find
#define arm_get_freespace ft->arm->get_freespace
#define arm_find_src_of_dest ft->arm->find_src_of_dest
#define arm_create_func ft->arm->create_func
#define arm_create_object_from_makefile ft->arm->create_object_from_makefile
#define arm_run_makefile ft->arm->run_makefile
#define arm_create_object ft->arm->create_object

#define MyDispatcher ft->seer->MyDispatcher
#define str ft->seer->str
#define seer_init ft->seer->init
#define seer_execute ft->seer->execute
#define seer_progresscallback ft->seer->progresscallback
#define seer_handle_include ft->seer->handle_include
#define seer_run ft->seer->run
#define seer_add_header ft->seer->add_header
#define seer_add_symbol_int ft->seer->add_symbol_int
#define seer_del_header ft->seer->del_header
#define seer_del_symbol_int ft->seer->del_symbol_int

#define project_free ft->project->free
#define project_create ft->project->create
#define project_init ft->project->init
#define project_add_file ft->project->add_file
#define project_get_file ft->project->get_file
#define project_del_file ft->project->del_file
#define project_load ft->project->load
#define project_save ft->project->save

#define mutex_create ft->mutex->create
#define mutex_release ft->mutex->release
#define mutex_lock ft->mutex->lock
#define mutex_locked ft->mutex->locked
#define mutex_unlock ft->mutex->unlock

#define mem_init ft->mem->init
#define mem_get_hash ft->mem->get_hash
#define mem_allocate ft->mem->allocate
#define mem_get_entry ft->mem->get_entry
#define mem_delete_old_entry ft->mem->delete_old_entry
#define mem_allocate_type ft->mem->allocate_type
#define mem_strduplicate ft->mem->strduplicate
#define mem_calloc ft->mem->calloc
#define mem_check ft->mem->check
#define mem_check_overwrite ft->mem->check_overwrite
#define mem_check_overwrites ft->mem->check_overwrites
#define mem_check_all ft->mem->check_all
#define mem_set_state_mark ft->mem->set_state_mark
#define mem_get_state_mark ft->mem->get_state_mark
#define mem_release_tagged ft->mem->release_tagged
#define mem_reallocate ft->mem->reallocate
#define mem_release ft->mem->release
#define mem_is_valid ft->mem->is_valid
#define mem_reallocate_seer ft->mem->reallocate_seer
#define mem_allocate_seer ft->mem->allocate_seer
#define mem_calloc_seer ft->mem->calloc_seer
#define mem_strduplicate_seer ft->mem->strduplicate_seer
#define mem_release_seer ft->mem->release_seer
#define mem_allocate_passthru ft->mem->allocate_passthru
#define mem_release_passthru ft->mem->release_passthru


#endif
